### ISSUE TITLE
Cesium for Unity doesn't compile on Unity 6.5

### ISSUE THREAD

**Issue by CisDutchRose** [CesiumGS/cesium-unity-samples#79]
Just started a new Unity 6.5 project with Cesium for Unity (latest from the scoped registry) but it won't compile anymore. The editor scripts still use the old non-generic `TreeView` / `TreeViewItem` / `TreeViewState`, which Unity deprecated and now removed in 6.5:

```
IonAssetsTreeView.cs(99,46): error CS0619: 'TreeView' is obsolete: ...use TreeView<int> instead
IonAssetsTreeView.cs(103,34): error CS0619: 'TreeViewState' is obsolete
IonAssetsTreeView.cs(138,28): error CS0619: 'TreeViewItem' is obsolete
CesiumIonAssetsWindow.cs(32,17): error CS0619: 'TreeViewState' is obsolete
```

These were just warnings back in 6.2, but 6.5 marks the types as removed and treats them as errors. Since the Cesium editor assembly fails to build, the `CesiumForUnity` namespace never gets generated, which then breaks Google's ARCore Geospatial Creator adapter with a pile of CS0246 "namespace not found" errors:

```
GeospatialCreatorCesiumAdapter.cs(26,11): error CS0246: 'CesiumForUnity' could not be found
```

**Repro:** fresh Unity 6.5 project → install latest Cesium via the scoped registry → enable ARCore Extensions + Geospatial Creator. Compile fails.

**Setup:** Unity 6.5 (6000.5), latest Cesium for Unity, ARCore Extensions with Geospatial Creator.

Looks like `IonAssetsTreeView.cs` and `CesiumIonAssetsWindow.cs` just need to move to the generic `TreeView<int>` API for 6.5+. Any tips for an temporary fix?

**Comment by CisDutchRose** [comment]
Sorry this is an duplicated and posted in the wrong GitHub..
